### ISSUE TITLE
Provide linter with stylus string directly instead of path.

### ISSUE THREAD

**Issue by florentpoujol** [SimenB/stylint#146]
Hey !

Could you add a way to provide the linter with the stylus string, instead of the path to a file or directory ?

I can do that with Stylus already by catching the error but it often doesn't give the proper line where it  happens, which is not that usefull...
So that's why I was looking at a proper linter.

**Comment by SimenB** [comment]
I'm looking into providing the possibility for this. Would make integrations with gulp/grunt (or any programmatic use) cleaner

**Comment by rossPatton** [comment]
Wouldn't be that hard really, would probably just be another branch in core/read.js

**Comment by SimenB** [comment]
@rossPatton What do you think about trying to line up with eslint's api? http://eslint.org/docs/developer-guide/nodejs-api
Providing one method that works on strings and takes an options-object returning an object with the result, and a few methods to work on files and retrieve formatters (reporters).

The first one is what is asked for in this issue, and the one that would probably be used for both the gulp and grunt plugin. It's quite similar to how CSSLint does it as well.

**Comment by rossPatton** [comment]
Sure, makes sense to me

**Comment by joezimjs** [comment]
+1 to paralleling eslint

**Comment by Anaphase** [comment]
+1 for this, would definitely help integrate stylint into my build process

**Comment by SimenB** [comment]
Please follow #274 for this
