### ISSUE TITLE
Visual Studio code extension

### ISSUE THREAD

**Issue by vtfn** [SimenB/stylint#306]
I wrote a little extension to integrate stylint into Visual Studio Code.
If it won't be a problem, could you list it along with the others (Sublime Text and Atom) in your README?

The link to the repo
https://github.com/vtfn/vscode-stylint

**Comment by rossPatton** [comment]
awesome, thanks for this! will add soon

**Comment by SimenB** [comment]
@vtfn Care to provide a PR adding a link to it?

**Comment by AdrianoCahete** [comment]
@SimenB This don't work anymore, like said in #418 

Can you remove that info from README and/or mark 418 as "help wanted" in readme for vscode?
