### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by eddiemonge** [SimenB/stylint#342]
Is this still being maintained? If not, could someone else take over or help out?

**Comment by rossPatton** [comment]
i do little things here and there, but no, i would not consider this project to be maintained

i have given a few people commit access, but i'd gladly hand over the entire project if someone wants it!

**Comment by SimenB** [comment]
I try to fix bugs if I'm made aware of them, but as I don't use stylus currently, it's less of a priority actively contributing.

Some day I'll finish up #274, but I that I won't have time for it in the foreseeable future.

Might be a thought to try to prioritize #269, which I think will facilitate easier testing, which should prevent regressions better.

And of course, the dream is #303 😄

**Comment by iDev0urer** [comment]
@rossPatton I'd be willing to take the project over

**Comment by rossPatton** [comment]
well, @SimenB has contributed the most, so I feel he should get first dibs

@SimenB you want to take over?

**Comment by SimenB** [comment]
@rossPatton, sure I can do that!

**Comment by rossPatton** [comment]
@SimenB request sent!

**Comment by SimenB** [comment]
@rossPatton Thanks!
@iDev0urer Please do submit PRs. I have no problem adding you as collaborator, just chuck a few PRs my way 😄

**Comment by SimenB** [comment]
@rossPatton Could you add me as owner on npm as well? Unless it's already done 😄

**Comment by rossPatton** [comment]
@SimenB should be good now. good luck!

**Comment by SimenB** [comment]
@rossPatton how did you generate the html docs?

**Comment by rossPatton** [comment]
i used [jsdoc](http://usejsdoc.org/about-getting-started.html)

**Comment by SimenB** [comment]
Ah! Didn't even know they had a package...

https://github.com/SimenB/stylint/commit/7e9af52f736271c956a7a2ac0dc841789e41b373
