### ISSUE TITLE
Rename reported error message properties

### ISSUE THREAD

**Issue by wojciechczerniak** [SimenB/stylint#366]
Instead of `lineNo` we could use `line` and instead of `col` use `column`. I won't say that we should copy ESLint in everything but it's how they named them 😄 We can name them `lineNo` and `columnNo`/`colNo` but be consistent.

**Comment by SimenB** [comment]
I totally agree. I was just about to create an issue about the structure of the object passed to reporters.

We should copy this: http://eslint.org/docs/developer-guide/nodejs-api#executeonfiles

**Comment by SimenB** [comment]
I've started on this: https://github.com/SimenB/stylint/tree/restructur-message-obj

Going OK; currently making the transformation in `done`. Have to write tests for it, plus update tests for `reporter`. But the implementations should be done
