### ISSUE TITLE
Update linting rules

### ISSUE THREAD

**Issue by SimenB** [SimenB/stylint#374]
I'm not a fan of the spaces within function calls, nor missing semis. There are also a bunch of other rules I'd like to activate.

I have a personal config (a few changes on top of airbnb), I'm thinking of just using that (https://github.com/SimenB/eslint-config-simenb/tree/master/packages/eslint-config-simenb-base).

@wojciechczerniak if you disagree with the rules, I'm open for just going with plain airbnb.

This will be done after #361 to avoid having to use `legacy` config

**Comment by wojciechczerniak** [comment]
Not a fan of missing semis either. But I can work with anything as long as files are consistent.

Rules look ok for me.

**Comment by rossPatton** [comment]
change whatever, but just fyi, semis are in fact totally unnecessary since javascript has automatic semicolon insertion

i do realize i'm in the minority on that opinion though

**Comment by SimenB** [comment]
I know, it's my Java background that taints me 😆

**Comment by SimenB** [comment]
@wojciechczerniak I'll do this now, gonna be big changes 😆

**Comment by SimenB** [comment]
Done...

https://github.com/SimenB/stylint/compare/0a078154e87a0548cba139388b9ec16722c84410...26f146b73f08a7af34fba86304f2663cff423da3
