### ISSUE TITLE
Git tag old releases

### ISSUE THREAD

**Issue by SimenB** [SimenB/stylint#376]
To fill out https://github.com/SimenB/stylint/releases

**Comment by emmabukacek** [comment]
@SimenB @rossPatton 

Went ahead and took care of this one. My process was to look at the `package.json` history, walk through each commit to find releases, compare those to the releases in `changelog.md`, then make tags using the date from the original commit where the `package.json` was actually bumped. Ran into a few snags, but I think we're mostly okay. Here are the unresolved items:

## Releases not included in `package.json`
Only found one, but `v1.1.1` was bumped in `package.json` without a `changelog.md` entry. I can try to put together a message for this and update the `changelog.md`, but I figured it would be easier for someone who was actually working in the code at the time.

## Ambiguous releases
Found a few instances where the `package.json` was bumped with the same version in more than one commit. Could be that I'm reading the commits incorrectly though, :laughing: .

* v1.0.10
  * https://github.com/SimenB/stylint/commit/a6158ca02efaa8f84d06448855a1f267d7d4f1e1 ( _Used this commit_ )
  * https://github.com/SimenB/stylint/commit/30cc41b80a4a7d3a7c0fe0dcf1595528fc896330#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
* v0.9.5
  * https://github.com/SimenB/stylint/commit/bf0fe425c6db318beafab4e5e9b203b296549447#diff-b9cfc7f2cdf78a7f4b91a753d10865a2t
  * https://github.com/SimenB/stylint/commit/fa1ee81ad674eda65f8cdde1cfef3da4e1802428#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 ( _Used this commit_ )

## Releases in `changelog.md` without a package.json bump
I don't think this is worth fretting about, but figured I'd record it here.
* v0.9.10
* v0.9.9
* v0.9.8

## Releases prior to v0.7.1
Would you like me to tag all `package.json` bumps prior to `v0.7.1`? I didn't see equivalent releases in the `changelog.md`, so I figured everything prior was trivial, but I'm happy to add those and use the commit messages to determine the changes.

I'll leave this issue open for now to be safe, but this issue should be more or less resolved. :smile:

**Comment by SimenB** [comment]
Thanks for taking care of it!

>Would you like me to tag all `package.json` bumps prior to `v0.7.1`?

I don't think it's really necessary, but feel free if you want to 🙂
