### ISSUE TITLE
Union with `stylelint`

### ISSUE THREAD

**Issue by evilebottnawi** [SimenB/stylint#383]
@SimenB 
Ref: https://github.com/stylelint/stylelint

Our good linter based on `postcss`.
This is only discussion
Can we join forces and create something truly powerful?

**Comment by SimenB** [comment]
I'd love to do that, but postcss would have to support stylus, which it does not.

Related to #303

**Comment by evilebottnawi** [comment]
@SimenB we can write own postcss parser as https://github.com/postcss/postcss-scss, https://github.com/webschik/postcss-less and use this in stylint.

**Comment by SimenB** [comment]
Sure, I'd love to have it. I'm not gonna spend time on it (yet), but I'd be happy to review/assist someone if they took the plunge.

postcss/postcss#602

**Comment by evilebottnawi** [comment]
I close due to inactivity, overload of issues
