### ISSUE TITLE
Auto-fix "sortOrder"

### ISSUE THREAD

**Issue by ThisIsManta** [SimenB/stylint#405]
Fixing "sortOrder" manually was so painful and the linting report was not really informative, i.e. it did not tell which came before which.

Could we have a command-line, just like `eslint --fix path-to-file`, so that the linter will re-sort them automatically?

**Comment by ThisIsManta** [comment]
Never mind, I have created my own tool to re-format the whole Stylus file and also re-order the CSS properties. https://thisismanta.github.io/stylus-supremacy/

**Comment by nojvek** [comment]
@ThisIsManta - Your vscode extension is absolutely f***-ing awesome. Saved me hours, let me know if there is charity you'd like me to donate to.

Although I really would like a native stylint --fix option as well

**Comment by ThisIsManta** [comment]
@nojvek, I appreciate your favorable comment. It's very lovely to hear that my work worths a donation, but I'm financially stable and it was a part of my job, so I'm fine. Thank you!

**Stylus Supremacy** is also available in [Node.js module](https://thisismanta.github.io/stylus-supremacy/#command-line) as well, so you can batch formatting Stylus files. I believe this is the closest thing to `stylint --fix`.

**Comment by nojvek** [comment]
Yeah I just used that to format close to 500 files. Since I didn’t have to write my own style fixer you saved me a day of hell. 

Also the vscode plugin is fantastic. Thanks a million for working on it.
