### ISSUE TITLE
``extendPref``  example contains a minor typo

### ISSUE THREAD

**Issue by yash-nisar** [SimenB/stylint#411]
Example if set to `@extend`: prefer `@extend $some-var` over `@extend $some-var` 
should be changed to 
Example if set to `@extend`: prefer `@extend $some-var` over `@extends $some-var`

**Comment by SimenB** [comment]
Could you send a PR with the fix?

**Comment by yash-nisar** [comment]
The PR is [here](https://github.com/SimenB/stylint/pull/412). @SimenB
