### ISSUE TITLE
Support for :export syntax

### ISSUE THREAD

**Issue by daniel-shuy** [SimenB/stylint#417]
stylint: 1.5.8
OS: Windows

The `:export` syntax is not officially documented, however it can be used in Stylus files to export variables to JavaScript. See stylus/stylus#2316.

Currently `stylint` complains that `:export` and the keys within the `:export` block are not valid properties.

**Comment by daniel-shuy** [comment]
Apparently `:export` is not a Stylus feature, but a `css-modules` feature. Apparently my `css-loader` module for Webpack was converting my Stylus files to css-modules.

Would it be right for `stylint` to support the `:export` syntax?

**Comment by SimenB** [comment]
Would the `mixins` config option be enough for you? https://github.com/SimenB/stylint/blob/master/README.md#transparent-mixins--custom-properties--array-

**Comment by daniel-shuy** [comment]
`customProperties` wouldn't be sufficient because `stylint` would still complain about the keys.

Apparently, simply annotating the entire `:export` block as a literal `@css` block does the job, thanks.
