### ISSUE TITLE
Recommended approach for vscode?

### ISSUE THREAD

**Issue by endquote** [SimenB/stylint#418]
The most discoverable approach for integrating stylint with vscode seems to be this plugin:
https://marketplace.visualstudio.com/items?itemName=vtfn.stylint

And I can install it, but it doesn't seem to do anything. Also the repository (and the repository's owner) seems to have gone away:
https://github.com/vtfn/vscode-stylint

Is there a more current approach?

It seems like making an eslint plugin might be the way to go.
http://eslint.org/docs/developer-guide/working-with-plugins

**Comment by AdrianoCahete** [comment]
Same here.

**Comment by AntonNiklasson** [comment]
Is there still no plugin available? I could spend some time on this if there's no other solution available.

**Comment by ThisIsManta** [comment]
I believe you need to `npm i stylint` locally (stylint must be present in your working package.json)
