### ISSUE TITLE
Should we add package-lock.json to .gitignore?

### ISSUE THREAD

**Issue by PalleZingmark** [SimenB/stylint#428]
Since node 8 and npm 5, `npm install` creates a `package-lock.json` to lock the versions of dependencies that are installed.
They recommend to commit this file, and that's what I usually do in normal projects when using NPM, but I think we should gitignore it in stylint as this will allow us to always test the latest version of the dependencies.

**Comment by SimenB** [comment]
PR welcome 🙂 

V2 branch uses yarn, FWIW
