### ISSUE TITLE
How can I configure the BEM naming convention?

### ISSUE THREAD

**Issue by Dzhakhar** [SimenB/stylint#431]
Can I provide any customization for the `namingConvention: "BEM"` property?

**Comment by SimenB** [comment]
Just set it to something else.

https://github.com/SimenB/stylint/blob/23b92fc8a7699c05c0b7c0bbc63bb389bd4fb03f/src/core/config.js#L49-L52

PR welcome for other styles if you need it

**Comment by Dzhakhar** [comment]
@SimenB thank you for your quick response.
Is `false` value set by default on `namingConventionStrict` ?

**Comment by Dzhakhar** [comment]
@SimenB is it possible to pass a BEM detecting regex (`bemRe`) as an option? To configure the BEM rules to my needs?

**Comment by SimenB** [comment]
PR welcome for that, yes.

I think it will have to be the path to a module then, as you can't pass functions directly

**Comment by Dzhakhar** [comment]
@SimenB can't I pass something like this `"/^([$.#{:][${a-z]([-]?[${}a-z0-9]+)*(_{2}[${}a-z0-9]([-]?[${}a-z0-9]+)*)?((_[${}a-z0-9]([-]?[a-z0-9}]+)*){2})*)\b/m"`?

**Comment by SimenB** [comment]
That works as well if a regexp is always enough

**Comment by SimenB** [comment]
>Is `false` value set by default on `namingConventionStrict` ?

yes

**Comment by SimenB** [comment]
It doesn't work now though, PR is needed for it

**Comment by Dzhakhar** [comment]
@SimenB I'm gonna contribute. Could you please get back to me via email or via skype dzhakhar1209 to discuss it

**Comment by SimenB** [comment]
I'm on holidays, so not available.

I would add a new option called `namingConventionRegexp` or `namingConventionPattern` (and require `namingConvention: "regexp"` or `namingConvention: "pattern"` depending on which you land on)

**Comment by Dzhakhar** [comment]
Got it! But will you be able to review my PR in case it comes today?
Have a nice holidays

**Comment by SimenB** [comment]
>But will you be able to review my PR in case it comes today?

Yes
